version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: rag-backend
    volumes:
      - ./backend:/backend                 # live code reload (backend code)
      - ./data:/backend/data               # mounting data folder inside container
      - ./.env:/backend/.env               # optional, if you rely on .env vars
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/backend
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag-frontend
    volumes:
      - ./frontend.py:/frontend/frontend.py  # live edits for Streamlit frontend
      - ./.env:/frontend/.env                 # optional env vars
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8000/api/qa
    depends_on:
      - backend
    env_file:
      - .env
