# Dockerfile.frontend
FROM python:3.10-slim

WORKDIR /app

COPY ./frontend.py /app/frontend.py
COPY ./requirements.frontend.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
