FROM python:3.11-slim

WORKDIR /frontend

COPY requirements_frontend.txt ./
RUN pip install --no-cache-dir -r requirements_frontend.txt

COPY frontend.py ./ 

EXPOSE 8501

CMD ["streamlit", "run", "frontend.py", "--server.address=0.0.0.0", "--server.port=8501"]
