version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile.backend
    container_name: changi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: changi-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
